### ISSUE TITLE
Rubric validation fails with an unexpected exception when grading

### ISSUE THREAD

**Issue by suhailrehman** [uchicago-cs/chisubmit#15]
Rubric validation fails for one student.

```bash
chisubmit grader validate-rubrics hw3 --only *STUDENT NAME REDACTED*      
ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/cli/common.py", line 92, in new_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/cli/common.py", line 61, in new_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/cli/common.py", line 82, in new_func
    return ctx.invoke(f, ctx.obj["course_obj"], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/cli/grader/__init__.py", line 130, in grader_validate_rubrics
    valid, error_msg = validate_repo_rubric(ctx, course, assignment, team, registration)
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/cli/common.py", line 406, in validate_repo_rubric
    RubricFile.from_file(open(rubricfile), assignment)
  File "/usr/local/lib/python2.7/dist-packages/chisubmit/rubric/__init__.py", line 212, in from_file
    (rc_description.description, rc_points_obtained, rc_points_possible))
AttributeError: 'str' object has no attribute 'description'
```
Rubric File is pasted here. Not sure if there's an offending character causing the process to breakdown.:

```
Points:
    - p1:
        Points Possible: 5
        Points Obtained: 5

    - p2:
        Points Possible: 5
        Points Obtained: 10

    - p3:
        Points Possible: 10
        Points Obtained: 10

    - p4:
        Points Possible: 10
        Points Obtained: 10

    - p5:
        Points Possible: 10
        Points Obtained: 10

    - p6:
        Points Possible: 10
        Points Obtained: 10

    - p7:
        Points Possible: 10
        Points Obtained: 10

    - p8:
        Points Possible: 10
        Points Obtained: 10

    - p9:
        Points Possible: 10
        Points Obtained: 5

    - p10a:
        Points Possible: 10
        Points Obtained: 8

    - p10b:
        Points Possible: 10
        Points Obtained: 8

Total Points: 95 / 100

Comments: >
    9.sql: Unable to verify your query since it timed out.
    10a.sql: Your answer does not match the reference solution.
    10b.sql: Your answer does not match the reference solution.
```

**Comment by suhailrehman** [comment]
Never mind, caught the bug p2 (more points assigned than possible)

**Comment by borjasotomayor** [comment]
fyi, the confusing error message is a know issue, and will be resolved this summer.
